const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { PGlite } = require('@electric-sql/pglite');

test('transactional variant editing preserves identity, stock and complete review totals', async () => {
  const pg = new PGlite();
  try {
    await pg.exec(`
      CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
      CREATE TABLE produtos(id bigint PRIMARY KEY, estoque integer, atualizado_em timestamptz DEFAULT now());
      CREATE TABLE produto_variantes(
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, produto_id bigint REFERENCES produtos(id),
        cor text NOT NULL, tamanho text NOT NULL, estoque integer NOT NULL CHECK(estoque >= 0),
        ativo boolean DEFAULT true, preco numeric, preco_antigo numeric, imagem_url text,
        imagens text[] DEFAULT '{}', videos text[] DEFAULT '{}', cor_hex text, ordem integer DEFAULT 0,
        criado_em timestamptz DEFAULT now(), atualizado_em timestamptz DEFAULT now(),
        UNIQUE(produto_id, cor, tamanho)
      );
      CREATE TABLE itens_pedido(id bigint PRIMARY KEY, produto_variante_id bigint REFERENCES produto_variantes(id) ON DELETE SET NULL);
      CREATE TABLE metricas_eventos(id bigint PRIMARY KEY, produto_variante_id bigint REFERENCES produto_variantes(id));
      CREATE TABLE avaliacoes_produtos(id bigint PRIMARY KEY, produto_id bigint, status text, nome_cliente text, nota integer, comentario text, criado_em timestamptz DEFAULT now());
      INSERT INTO produtos VALUES(1,5,now()),(2,5,now());
      INSERT INTO produto_variantes(produto_id,cor,tamanho,estoque) VALUES(1,'Preto','M',3),(1,'Preto','G',2),(2,'Azul','M',5);
      INSERT INTO itens_pedido VALUES(1,1);
    `);
    await pg.exec(fs.readFileSync(path.join(__dirname, '../supabase/migrations/20260916191122_audit_integrity.sql'), 'utf8'));
    const save = variants => pg.query('SELECT salvar_variantes_seguras(1, $1::jsonb) AS result', [JSON.stringify(variants)]);
    const variant = { id: 1, cor: 'Preto', tamanho: 'M', estoque: 3, estoque_original: 3, ativo: true, preco: 99, imagens: ['new.jpg'], videos: [] };
    const first = await save([variant]);
    assert.equal(first.rows[0].result[0].id, 1);
    assert.equal((await pg.query('SELECT produto_variante_id FROM itens_pedido')).rows[0].produto_variante_id, 1);
    assert.equal((await pg.query('SELECT ativo FROM produto_variantes WHERE id=2')).rows[0].ativo, false);
    assert.equal((await pg.query('SELECT estoque FROM produtos WHERE id=1')).rows[0].estoque, 3);

    // A sale while the admin edits a photo must not restore the sold unit.
    await pg.exec('UPDATE produto_variantes SET estoque=2 WHERE id=1');
    await save([variant]);
    assert.equal((await pg.query('SELECT estoque FROM produto_variantes WHERE id=1')).rows[0].estoque, 2);
    await assert.rejects(save([{ ...variant, estoque: 4 }]), /Estoque mudou/);
    assert.equal((await pg.query('SELECT estoque FROM produto_variantes WHERE id=1')).rows[0].estoque, 2);

    // One invalid row rolls back all earlier changes in the same request.
    await assert.rejects(save([{ ...variant, imagem_url: 'not-saved.jpg' }, { ...variant, id: 3, cor: 'Azul' }]), /Variacao alterada/);
    assert.equal((await pg.query('SELECT imagem_url FROM produto_variantes WHERE id=1')).rows[0].imagem_url, null);
    await assert.rejects(save([variant, { ...variant, id: null }]), /duplicada/);
    await assert.rejects(save([{ ...variant, estoque_original: null }]), /Reabra/);
    await save([{ ...variant, estoque_original: 2, estoque: 2 }, { cor: 'Azul', tamanho: 'P', estoque: 4, ativo: true, imagens: [], videos: [] }]);
    assert.equal((await pg.query('SELECT estoque FROM produtos WHERE id=1')).rows[0].estoque, 6);
    await save([]);
    assert.equal((await pg.query('SELECT produto_variante_id FROM itens_pedido')).rows[0].produto_variante_id, 1);
    assert.equal((await pg.query('SELECT estoque FROM produtos WHERE id=1')).rows[0].estoque, 0);

    await pg.exec(`INSERT INTO avaliacoes_produtos(id,produto_id,status,nome_cliente,nota,comentario)
      SELECT i,1,'aprovada','Cliente',CASE WHEN i<=30 THEN 5 ELSE 1 END,'Texto teste' FROM generate_series(1,35) i;
      INSERT INTO avaliacoes_produtos VALUES(36,1,'pendente','Privado',1,'Nao publicar',now());`);
    const read = async page => (await pg.query('SELECT avaliacoes_paginadas(1,$1) AS result', [page])).rows[0].result;
    const reviews = await read(1);
    assert.equal(reviews.total, 35);
    assert.equal(reviews.avaliacoes.length, 6);
    assert.ok(Math.abs(reviews.media - 155 / 35) < 0.0001);
    assert.equal((await read(6)).avaliacoes.length, 5);
    const ids = [];
    for (let i = 1; i <= 6; i++) ids.push(...(await read(i)).avaliacoes.map(row => row.id));
    assert.equal(new Set(ids).size, 35);
    assert.ok(!ids.includes(36));
    assert.equal((await pg.query("SELECT has_function_privilege('anon','salvar_variantes_seguras(bigint,jsonb)','EXECUTE') AS allowed")).rows[0].allowed, false);
    assert.equal((await pg.query("SELECT has_function_privilege('anon','avaliacoes_paginadas(bigint,integer)','EXECUTE') AS allowed")).rows[0].allowed, false);
  } finally { await pg.close(); }
});
